### ISSUE TITLE
My Private Videos on Youtube can't access; went back to 5.3, & access is perfect

### ISSUE THREAD

**Issue by mamnnn** [TheRealJoelmatic/RemoveAdblockThing#611] opened 2024-06-13 12:48 UTC
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by vagman** [comment] 2024-06-13 14:28
Duplicate of #597 , you can delete it.

**Closed** 2024-06-15 14:48 UTC
