### ISSUE TITLE
my ad center opens

### ISSUE THREAD

**Issue by Altex2** [TheRealJoelmatic/RemoveAdblockThing#190] opened 2023-12-09 22:01 UTC
The window in te screenshot opens every time a new video starts... I am on safari on Mac and I am using "Userscripts" to run the js script.
<img width="714" alt="Screenshot 2023-12-10 at 00 00 42" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/82447550/f1ab71c7-4355-42a8-af22-5210042c54be">

**Comment by r290085** [comment] 2023-12-09 23:02
also got the ad center pop up

**Comment by MrSteff** [comment] 2023-12-10 01:05
Yea same to me, Is it because of the script?

**Comment by duggum** [comment] 2023-12-10 02:13
Thought it was a Chrome thing, so I switched to Firefox. Same issue in both browsers.

**Comment by waynerigley** [comment] 2023-12-10 03:46
Same here but just started today 12-09-2023 does it at the start of the videos and also during the videos. hope there is an update soon..

**Comment by BrorsanP2** [comment] 2023-12-10 03:59
Same

**Comment by WesleyTRV** [comment] 2023-12-10 04:35
Same goes to me, this needs a proper quick fix patch pronto.

**Comment by konrel** [comment] 2023-12-10 05:37
Same issue here.

Dirty workaround for now - Use Stylus or Tweaks for YouTube and add this into the CSS to hide the popup:

body > ytd-app > ytd-popup-container > tp-yt-paper-dialog {
  display: none;
}

**Comment by supersmith2500** [comment] 2023-12-10 12:55
I tried this method that @Altex2 used and I'm still getting those annoying Ad Center pop-ups.
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/193

**Comment by TheRealJoelmatic** [comment] 2023-12-10 15:51
This should be fixed in the latest version (2.6)

**Comment by mickleby** [comment] 2023-12-10 16:16
I thought today's update would address this, but it doesn't. I'm still launching the My Ad Center popup 🫤

**Comment by mickleby** [comment] 2023-12-10 16:30
> Stylus or Tweaks for YouTube

I think you mean the separate Chrome extensions. I installed Stylus and added your code 👍

Thanks!

**Comment by Necrome397** [comment] 2023-12-10 17:13
2.6 seems to not have changed anything. First thing I got was the flashing white screen followed by the ad center popup which I had to close manually.

**Comment by konrel** [comment] 2023-12-10 17:37
2.6 fixed the issues for me.
Try deleting the script completely, restarting your browser fully, and re-adding.
When I was messing with it yesterday I noticed Tampermonkey wasn't fully reloading it for me.

**Comment by ralinchan** [comment] 2023-12-10 19:12
> 2.6 seems to not have changed anything. First thing I got was the flashing white screen followed by the ad center popup which I had to close manually.

Confirming @konrel 

2.6 appears to have addressed the persisting ad center. The white flashes will still occur likely the new way to combat google's greed trying to prevent adblockers.

**Comment by TheRealJoelmatic** [comment] 2023-12-10 20:08
Is there any way to reproduce the white flashes as I cant personally on my machine.

**Comment by Altex2** [comment] 2023-12-10 20:11
> Is there any way to reproduce the white flashes as I cant personally on my machine.

The main problem for me rn is that i keep getting the you are using an adblocker and i need to refresh every 2 songs ... and yeah when this happens it keeps skipping to the next song in the mix .. i will try to fix it tomorrow, today i am busy

**Comment by ralinchan** [comment] 2023-12-10 21:46
> Is there any way to reproduce the white flashes as I cant personally on my machine.

The only steps I can think of is having any video that is preceded by ads. It's not a full screen flash, it basically appears to be a rendering of the ad center frame. I'm not doing anything specific to cause it to happen, just updated to 2.5 yesterday (and then 2.6 today) and it will happen 100% of the time any time it is blocking an ad at the start of a video (so if 2 ads play, the frame will flash twice). It does not appear to ever occur for blocking an ad that occurs mid stream/mid video.

This is on FF 120.0.1 with ublock disabled on youtube

**Comment by Necrome397** [comment] 2023-12-11 02:39
Yes, most of the time when there is an add which has the skip button in the right lower corner. When the white flashing screen appears it's hard to hit the skip button because the white screen covers it. And sometimes when the flashing it over it becomes the ad center window. Happens on Chrome and Firefox.

________________________________
Von: Joelmatic ***@***.***>
Gesendet: Sonntag, 10. Dezember 2023 21:09
An: TheRealJoelmatic/RemoveAdblockThing ***@***.***>
Cc: Necrome397 ***@***.***>; Mention ***@***.***>
Betreff: Re: [TheRealJoelmatic/RemoveAdblockThing] my ad center opens (Issue #190)


Is there any way to reproduce the white flashes as I cant personally on my machine.

**Comment by Necrome397** [comment] 2023-12-11 03:00
[https://res.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]6a30c481-74e7-4d50-a2d1-222e6b6cfebc.mp4<https://1drv.ms/v/s!AlSSSXKeg_OHhDyws8RvuG86Q3h4>

This is what it looks like. I hope that link works.
________________________________
Von: S. Bochert ***@***.***>
Gesendet: Montag, 11. Dezember 2023 03:39
An: TheRealJoelmatic/RemoveAdblockThing ***@***.***>
Betreff: AW: [TheRealJoelmatic/RemoveAdblockThing] my ad center opens (Issue #190)

Yes, most of the time when there is an add which has the skip button in the right lower corner. When the white flashing screen appears it's hard to hit the skip button because the white screen covers it. And sometimes when the flashing it over it becomes the ad center window. Happens on Chrome and Firefox.

________________________________
Von: Joelmatic ***@***.***>
Gesendet: Sonntag, 10. Dezember 2023 21:09
An: TheRealJoelmatic/RemoveAdblockThing ***@***.***>
Cc: Necrome397 ***@***.***>; Mention ***@***.***>
Betreff: Re: [TheRealJoelmatic/RemoveAdblockThing] my ad center opens (Issue #190)


Is there any way to reproduce the white flashes as I cant personally on my machine.

**Closed** 2024-01-20 11:23 UTC
